name: middleman-build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Tailwind CSS build
        run: |
          bun install
          bunx @tailwindcss/cli -i ./source/stylesheets/site.css -o ./build/stylesheets/site.css --minify

      - name: Middleman Build
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
        run: NO_CONTRACTS=true bundle exec middleman build

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
