name: middleman-build

on:
  push:
    branches: [ main ]

jobs:
  build-HTML:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Middleman Build
        run: NO_CONTRACTS=true bundle exec middleman build

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: ./build

  build-CSS:
    needs: build-HTML
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: ./build

      - name: Tailwind CSS build
        run: |
          bun install
          bunx @tailwindcss/cli -i ./source/stylesheets/site.css -o ./build/stylesheets/site.css --minify

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-CSS
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
