name: build

on:
  push:
    branches: [ main ]

jobs:
  tailwindcss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Tailwind CSS build
        run: |
          bun install
          bunx @tailwindcss/cli -i ./assets/tailwind.css -o ./assets/styling/main.css --minify

      - name: Upload tailwindcss
        uses: actions/upload-artifact@v4
        with:
          name: main-css
          path: ./assets

  build-dioxus:
    needs: tailwindcss
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
            - stable
    steps:
      - uses: actions/checkout@v4

      - name: Download tailwindcss
        uses: actions/download-artifact@v4
        with:
          name: main-css
          path: ./assets

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Rustup prepare
        run: |
          rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
          rustup target add wasm32-unknown-unknown

      - name: Binstall dioxus-cli
        run: |
          cargo install cargo-binstall
          cargo binstall dioxus-cli

      - name: Cargo install
        run: cargo install --path .

      - run: dx bundle --platform web
